apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  labels:
    app: events-service
    component: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: ghcr.io/sergletterbox/architecture-cinemaabyss/events-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka-service:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/events/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/events/ready
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  selector:
    app: events-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP